---
- name: install nginx
  apt:
    name: nginx
    state: latest
  when: install_nginx
- name: install php
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - php5-curl
    - php5-imagick
    - php5-cli
    - php5-json
    - php5-fpm
    - php5-mysql
  when: install_php
- name: install mysql
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - mysql-common
    - mysql-server
    - mysql-client
    - python-mysqldb
  when: install_mysql
- name: config mysql passwd
  mysql_user:
    login_user: root
    login_password: "\n"
    name: root
    password: "voidking"
    host: "{{item}}"
    priv: '*.*:ALL,GRANT'
    state: present
    check_implicit_admin: yes
  with_items:
    - "localhost"
    - "%"
  when: install_mysql
- name: comment bind-address
  shell: sed -i 's/^bind-address/#bind-address/g' /etc/mysql/my.cnf
  when: install_mysql
- name: restart mysql service
  service: 
    name: mysql 
    state: restarted
    enabled: true
  when: install_mysql
- name: install haproxy
  apt:
    name: haproxy
    state: latest
  environment:
    RUNLEVEL: 1
  when: install_haproxy
- name: config haproxy
  shell: sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy
  when: install_haproxy
- name: config haproxy port
  copy: 
    src: ../files/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    force: yes
  when: install_haproxy
- name: restart haproxy
  service:
    name: haproxy
    state: restarted
  when: install_haproxy
